@@
@@
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(4,12,0)
NL_SET_ERR_MSG_MOD(...);
+#endif /* LINUX_VERSION_CODE < KERNEL_VERSION(4,12,0) */

@@
@@
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(6,2,0)
NL_SET_ERR_MSG_FMT_MOD(...);
+#endif /* LINUX_VERSION_CODE >= KERNEL_VERSION(6,2,0) */